#!/bin/bash

DEPLOYPATH=/home/coopecab/api.coopecabk.com/

rsync -av --delete --exclude='.git' /home/coopecab/repositories/api_abk/ $DEPLOYPATH

cd $DEPLOYPATH

source /home/coopecab/virtualenv/api.coopecabk.com/3.10/bin/activate

pip install -r requirements.txt

python manage.py migrate --noinput

python manage.py collectstatic --noinput

touch /home/coopecab/api.coopecabk.com/tmp/restart.txt
